### ISSUE TITLE
redo does not work with my version of janet

### ISSUE THREAD

**Issue by xrd** [ianthehenry/toodle.studio#1]
I didn't have janet installed, so I added to shell.nix. But, redo does not like it. 

(thanks for using shell.nix, it makes setup here so easy!)

I did do `yarn install` in root and ui directory beforehand, btw.

```
[nix-shell:~/Projects/toodle.studio]$ git diff
diff --git a/shell.nix b/shell.nix
index ae57746..1f362da 100644
--- a/shell.nix
+++ b/shell.nix
@@ -7,5 +7,6 @@ mkShell {
     pandoc
     nodejs
     redo-apenwarr
+    janet
   ];
 }
[nix-shell:~/Projects/toodle.studio]$ janet -v
1.21.2-release

[nix-shell:~/Projects/toodle.studio]$ redo
redo  all
redo    build/public.tree
redo      (main.css)
redo      build/mode
redo      build/all.js
redo        build/wasm.js
redo          build/toodles.jimage
error: src/gl/builtins.janet:12:1: compile error: macro arity mismatch, expected at least 3, got 1
  in dofile [boot.janet] (tailcall) on line 2744, column 7
  in source-loader [boot.janet] on line 2754, column 15
  in require-1 [boot.janet] on line 2774, column 18
  in import* [boot.janet] on line 2805, column 15
  in _thunk [src/helpers.janet] (tailcall) on line 1, column 1
  in dofile [boot.janet] (tailcall) on line 2743, column 7
  in source-loader [boot.janet] on line 2754, column 15
  in require-1 [boot.janet] (tailcall) on line 2774, column 18
  in _thunk [src/evaluator.janet] (tailcall) on line 6, column 30
  in dofile [boot.janet] (tailcall) on line 2743, column 7
  in source-loader [boot.janet] on line 2754, column 15
  in require-1 [boot.janet] on line 2774, column 18
  in import* [boot.janet] on line 2805, column 15
  in _thunk [src/init.janet] (tailcall) on line 1, column 1
  in dofile [boot.janet] on line 2743, column 7
  in c-switch [boot.janet] (tailcall) on line 3696, column 19
  in cli-main [boot.janet] on line 3733, column 13
redo          build/toodles.jimage (exit 1)
redo        build/wasm.js (exit 1)
redo      build/all.js (exit 1)
redo    build/public.tree (exit 1)
redo  all (exit 1)


```

**Comment by ianthehenry** [comment]
Yeah, the README should definitely document this, but you have to compile with the same version of Janet that's vendored in the `janet/` subdirectory (currently 1.26.0), because there's no image stability guarantee across Janet versions.

I don't have Janet in my nix shell because the `jpm` derivation in Nixpkgs doesn't have the right include paths (maybe it does now? I haven't checked in a while), so you can't use it to compile native modules. Which makes it unusable for most things I do. I don't think it would be much work to fix the derivation but I just install Janet from source instead...

The specific error you're seeing is about the addition of the `&named` syntax in https://github.com/janet-lang/janet/releases/tag/v1.23.0. But it probably uses other newer features as well.

**Comment by ianthehenry** [comment]
Probably a better thing to do is stop vendoring Janet altogether and to link against the user's `janet.h`. That way at least future users wouldn't have to downgrade your Janet to build this... but there will still be a minimum version requirement, though, so it wouldn't work Janet 1.21.0 anyway.

I mean an even better thing would be to use some kind of Janet version manager... but that doesn't exist as far as I know. I could see making some kind of a Janet-versions Nix flake that we could import... but that does not exist as far as I know.

**Comment by ianthehenry** [comment]
documented the dependency here https://github.com/ianthehenry/toodle.studio/commit/2c6b03e981169485c09101113772914588d0fd15
